### ISSUE TITLE
Tiny bug

### ISSUE THREAD

**Issue by az-ja** [feihuzhang/SeparableFlow#5]
Dear Feihu,

Thank you again for sharing your great research with us!
For running the code on a single GPU, I got this tiny error:
local variable 'val_sampler2_2' referenced before assignment.
Basically replacing the line 325 with
```
val_sampler2_1 = None 
val_sampler2_2 = None
```
fixed the issue.

With kind regards,
Azin

**Comment by feihuzhang** [comment]
Thanks for help with the bugs. 
Currently, please consider using the default multiprocessing_distributed mode for training.
We haven't test the non-distributed training yet.
